name: Test Action

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run
      uses: ./
      id: tag
      run: |
        GITHUB_REF=refs/heads/master node ./main.js || true
        GITHUB_REF=refs/tags/v1.0.0 node ./main.js
    - name: Test
      run: |
        test "v1.0.0" = ${{steps.tag.outputs.tag}}
